# Generated by Django 2.2.2 on 2019-06-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(),
        ),
    ]
