#!/bin/sh
#
#$ -N nom_par_defaut
#
#$ -l h_cpu=hh:mm:ss
#$ -l s_cpu=hh:mm:ss
#$ -l s_vmem=800M
#$ -P ctom
#$ -pe mpi 2
#
#$ -cwd
#$ -S /bin/sh

. /share/programs/bin/functions_jobs.sh

#trap 'CleanExit 15' 15
#trap 'CleanExit 24' 24
#trap 'CleanExit 30' 30
#trap 'CleanExit 31' 31

export PARNODES=$(( ${NSLOTS} - 0 ))
export PARA_ARCH=SMP

export HOSTS_FILE=./hostsfile
rm ${HOSTS_FILE}
for ((i=1; i<=${PARNODES}; i=${i}+1))
do
  hostname  >> ${HOSTS_FILE}
done

module unload turbomole
module   load turbomole_smp
